export const SCENARIO_CONFIG = {
    desert_island: {
        id: "desert_island",
        name: "Desert Island",
        subtitle: "Tropical Survival",
        difficulty: 1,
        totalDays: 5,
        description: "Your boat capsized near an uncharted island. With limited supplies washed ashore, your team must survive until rescue arrives. Build shelter, purify water, and signal for help.",
        bgColor: [25, 45, 35],
        accentColor: [60, 180, 100],
        startResources: { food: 60, water: 40, materials: 50 },
        dailyConsumption: { food: 12, water: 16, materials: 0 },
        days: [
            {
                day: 1,
                title: "Landfall",
                briefing: "Day 1: You wash ashore with scattered supplies. Fresh water is the priority -- dehydration kills in days.",
                puzzleId: "water_purification",
                event: null,
                resourceBonus: { food: 5, water: 0, materials: 10 },
            },
            {
                day: 2,
                title: "Storm Warning",
                briefing: "Day 2: Dark clouds gather on the horizon. Navi says a storm hits tonight. You need shelter NOW.",
                puzzleId: "shelter_construction",
                event: {
                    type: "storm",
                    name: "Tropical Storm",
                    description: "Winds of 80 km/h tear across the island. Without proper shelter, team health drops sharply.",
                    healthDamage: 25,
                    mitigatedBy: "shelter_construction",
                    mitigationReduction: 0.8,
                },
                resourceBonus: { food: 0, water: 10, materials: 0 },
            },
            {
                day: 3,
                title: "Fever Strikes",
                briefing: "Day 3: Juno is running a fever. Contaminated water? Insect bite? Kit needs to diagnose and treat it fast.",
                puzzleId: "medical_diagnosis",
                event: {
                    type: "sickness",
                    name: "Tropical Fever",
                    description: "One team member is gravely ill. Without treatment, they cannot contribute for 2 days.",
                    healthDamage: 15,
                    mitigatedBy: "medical_diagnosis",
                    mitigationReduction: 0.9,
                },
                resourceBonus: { food: 8, water: 5, materials: 5 },
            },
            {
                day: 4,
                title: "Rival Camp",
                briefing: "Day 4: Navi spotted smoke from another camp across the ridge. Another group of survivors -- do you trade or compete?",
                puzzleId: "resource_negotiation",
                event: {
                    type: "encounter",
                    name: "Rival Survivors",
                    description: "Another team of survivors needs materials. You can trade resources or risk conflict.",
                    healthDamage: 0,
                    mitigatedBy: "resource_negotiation",
                    mitigationReduction: 1.0,
                },
                resourceBonus: { food: 0, water: 0, materials: 15 },
            },
            {
                day: 5,
                title: "Rescue Signal",
                briefing: "Day 5: A plane is spotted in the distance! You have one chance to build and power a signal device. Every team member's knowledge is critical.",
                puzzleId: "signal_boost",
                event: {
                    type: "rescue_window",
                    name: "Rescue Aircraft",
                    description: "A search plane passes overhead. Your signal must be strong enough to reach it.",
                    healthDamage: 0,
                    mitigatedBy: "signal_boost",
                    mitigationReduction: 1.0,
                },
                resourceBonus: { food: 0, water: 0, materials: 0 },
            },
        ],
    },

    space_station: {
        id: "space_station",
        name: "Space Station",
        subtitle: "Orbital Emergency",
        difficulty: 2,
        totalDays: 5,
        description: "Micrometeorite impact has damaged your space station. Life support is failing, communications are down, and the escape pod needs repairs. Work together or drift forever.",
        bgColor: [8, 12, 30],
        accentColor: [100, 180, 255],
        startResources: { food: 50, water: 50, materials: 40 },
        dailyConsumption: { food: 10, water: 10, materials: 5 },
        days: [
            {
                day: 1,
                title: "Oxygen Crisis",
                briefing: "Day 1: Oxygen levels dropping. The CO2 scrubber took a hit. You need to repair the recycling system before everyone suffocates.",
                puzzleId: "oxygen_recycling",
                event: null,
                resourceBonus: { food: 0, water: 0, materials: 8 },
            },
            {
                day: 2,
                title: "Hull Breach",
                briefing: "Day 2: Sensors show a micro-fracture in Module B. Pressure is leaking slowly. Patch it before it blows.",
                puzzleId: "hull_repair",
                event: {
                    type: "pressure_loss",
                    name: "Hull Micro-Fracture",
                    description: "Air is escaping through a hairline crack. Patch it with the right sealant mixture or lose a module.",
                    healthDamage: 20,
                    mitigatedBy: "hull_repair",
                    mitigationReduction: 0.85,
                },
                resourceBonus: { food: 5, water: 5, materials: 0 },
            },
            {
                day: 3,
                title: "Solar Flare",
                briefing: "Day 3: A massive solar flare is incoming. You need to reroute power to shield the electronics or lose all navigation.",
                puzzleId: "solar_panel_fix",
                event: {
                    type: "solar_flare",
                    name: "Coronal Mass Ejection",
                    description: "Intense radiation threatens all unshielded electronics. Reconfigure the solar array to absorb and redirect.",
                    healthDamage: 15,
                    mitigatedBy: "solar_panel_fix",
                    mitigationReduction: 0.9,
                },
                resourceBonus: { food: 0, water: 0, materials: 10 },
            },
            {
                day: 4,
                title: "Communication Window",
                briefing: "Day 4: Ground control will pass within communication range for 4 minutes. Fix the relay or miss the window entirely.",
                puzzleId: "communication_relay",
                event: {
                    type: "comm_window",
                    name: "Ground Control Pass",
                    description: "Brief alignment with a ground station. Successful contact means rescue coordinates.",
                    healthDamage: 0,
                    mitigatedBy: "communication_relay",
                    mitigationReduction: 1.0,
                },
                resourceBonus: { food: 5, water: 5, materials: 5 },
            },
            {
                day: 5,
                title: "Escape Pod",
                briefing: "Day 5: The escape pod is your only way home. Navigation, life support, heat shielding -- everything must be perfect for re-entry.",
                puzzleId: "escape_pod_launch",
                event: {
                    type: "final_escape",
                    name: "Re-Entry Window",
                    description: "One shot at re-entry. Every system must be calibrated: angle, heat shield, parachute timing.",
                    healthDamage: 0,
                    mitigatedBy: "escape_pod_launch",
                    mitigationReduction: 1.0,
                },
                resourceBonus: { food: 0, water: 0, materials: 0 },
            },
        ],
    },

    underwater_base: {
        id: "underwater_base",
        name: "Underwater Base",
        subtitle: "Deep Sea Crisis",
        difficulty: 3,
        totalDays: 5,
        description: "An earthquake has damaged your deep-sea research station. The surface elevator is offline, pressure seals are cracking, and something large is circling outside. Improvise, adapt, survive.",
        bgColor: [5, 18, 35],
        accentColor: [60, 200, 190],
        startResources: { food: 45, water: 55, materials: 35 },
        dailyConsumption: { food: 11, water: 8, materials: 8 },
        days: [
            {
                day: 1,
                title: "Pressure Alert",
                briefing: "Day 1: Warning klaxons blare. The main pressure seal in Lab C is cracked. Fix it or the ocean pours in.",
                puzzleId: "pressure_seal",
                event: null,
                resourceBonus: { food: 5, water: 0, materials: 8 },
            },
            {
                day: 2,
                title: "Water Recycling",
                briefing: "Day 2: The desalination unit is offline. You are surrounded by water you cannot drink. Ironic. Fix the filters.",
                puzzleId: "deep_water_filtration",
                event: {
                    type: "system_failure",
                    name: "Desalination Failure",
                    description: "Drinking water reserves are low. The membrane filters need recalibrating with available chemicals.",
                    healthDamage: 15,
                    mitigatedBy: "deep_water_filtration",
                    mitigationReduction: 0.85,
                },
                resourceBonus: { food: 0, water: 15, materials: 0 },
            },
            {
                day: 3,
                title: "Creature Contact",
                briefing: "Day 3: Something massive just slammed into the observation deck. The glass is holding -- barely. Reinforce it and figure out what it wants.",
                puzzleId: "specimen_containment",
                event: {
                    type: "creature_attack",
                    name: "Deep Sea Predator",
                    description: "A large bioluminescent creature is ramming the station. Bright lights and specific frequencies may drive it away.",
                    healthDamage: 20,
                    mitigatedBy: "specimen_containment",
                    mitigationReduction: 0.8,
                },
                resourceBonus: { food: 10, water: 0, materials: 5 },
            },
            {
                day: 4,
                title: "Volcanic Vent",
                briefing: "Day 4: A nearby volcanic vent is heating up. The temperature spike could melt exterior cables -- or you could harness it for power.",
                puzzleId: "vent_analysis",
                event: {
                    type: "volcanic_activity",
                    name: "Thermal Vent Surge",
                    description: "Rising temperatures threaten hull integrity but could power the emergency beacon if properly channeled.",
                    healthDamage: 10,
                    mitigatedBy: "vent_analysis",
                    mitigationReduction: 0.9,
                },
                resourceBonus: { food: 0, water: 0, materials: 15 },
            },
            {
                day: 5,
                title: "Surface Signal",
                briefing: "Day 5: A rescue sub has been dispatched but needs your exact coordinates. Deploy the emergency buoy and pray the signal reaches.",
                puzzleId: "surface_signal",
                event: {
                    type: "rescue_window",
                    name: "Rescue Submersible",
                    description: "A rescue sub is searching the area. Deploy the emergency buoy with the correct ballast and signal frequency.",
                    healthDamage: 0,
                    mitigatedBy: "surface_signal",
                    mitigationReduction: 1.0,
                },
                resourceBonus: { food: 0, water: 0, materials: 0 },
            },
        ],
    },
};

export function getScenario(scenarioId) {
    return SCENARIO_CONFIG[scenarioId];
}

export function getScenarioList() {
    return Object.values(SCENARIO_CONFIG);
}
